### ISSUE TITLE
Appropriate use of Spo2 and Respiratory rate when patient is vented

### ISSUE THREAD

**Issue by sreered** [BorgwardtLab/mgp-tcn#2]
Your dataset doesn't seem to take into account that Spo2 and Respiratory rate [RR] might not be accurate if patient is on vent at that point in time. Wouldn't this impact your model?

Because patients Spo2 and RR would be artifically supported when vented.

**Comment by mi92** [comment]
This is an interesting point. I would predict that for several variables there is room for improvement. Maybe a solution to the vent problem would be to always feed the vent status at each point in time?  Whether this has an impact I don't know at this point, but would be interesting to know

**Comment by sreered** [comment]
thanks for your quick reply @mi92. My current hypothesis is it might, I will run some experiments and report back here. 

I will close the issue for now.
